version: "3"

services:
  
  loadbalencer:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - service
  
  service:
    build: .
    deploy:
      mode: replicated
      replicas: 2

  redis-server:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    expose:
      - 6379